# Generated by Django 2.2.1 on 2019-06-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibCalculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='result',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='number',
            field=models.IntegerField(default=None),
        ),
    ]
