# Generated by Django 2.2.1 on 2019-06-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fibCalculator', '0003_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
