# Generated by Django 2.2.1 on 2019-06-03 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fibCalculator', '0007_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
