# Generated by Django 2.2.1 on 2019-06-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibCalculator', '0008_remove_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
