# Generated by Django 2.2.3 on 2019-07-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibCalculator', '0009_auto_20190603_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='result',
            field=models.CharField(default=None, max_length=10000),
        ),
    ]
